### ISSUE TITLE
Ensure each _episode has a top-level summary at the start. 

### ISSUE THREAD

**Issue by hollandjg** [INTERSECT-training/packaging#17]
- [x] _episodes/01-environment.md #71 
- [x] _episodes/02-jupyter-to-package.md #72 
- [x] _episodes/03-other-files.md #59 
- [x] _episodes/04-metadata.md #16 
- [x] _episodes/05-versioning.md #18 
- [x] _episodes/06-documentation.md #64 
  - [x] Sphinx #64 
  - [x] MkDocs #65 
- [x] _episodes/07-checks.md #66 
- [x] _episodes/08-continuous-integration.md #68 
- [x] _episodes/09-publishing-citations.md #69

**Comment by hollandjg** [comment]
Done this now.
