### ISSUE TITLE
Update all files

### ISSUE THREAD

**Issue by hollandjg** [INTERSECT-training/packaging#35]
- _episodes
  - [x] #12 
  - [x] #13 
  - [x] #15 
  - [x] #16 
  - [x] #18 
  - [x] #19 
  - [x] #20 
  - [x] #21 
  - [x] #22 
- .devcontainer
  - [x] #23 
- fig
  - [x] fig/viewtoken.png #24 
- [x] #36 
- [x] .gitignore – no changes needed
- [x] #25 
- [x] aio.md – no changes needed
- [x] #27
- [x] #28
- [x] CODE_OF_CONDUCT.md – no changes needed
- [x] CONTRIBUTING.md – no changes needed
- [x] discuss.md – #93 
- [x] figures.md – no changes needed
- [x] #29
  - Gemfile, 
  - Gemfile.lock
- [x] #30
- [x] #31
- [x] LICENSE.md – no updates needed
- [x] #32
- [x] #33
- [x] #34

**Comment by hollandjg** [comment]
Updated all the files, closing this now.
